### ISSUE TITLE
Measure changes the order of qubits

### ISSUE THREAD

**Issue by eliskleen** [DATX11-22/Quaru#8]
A `Register` instantiated with `Register::new([state, state2])` does not reproduce the given states when their qubit positions are measured immediately after:
`[register.measure(0), register.measure(1)] != [state, state2]`

**Comment by BAMF0** [comment]
I think that the most natural and intuitive thing is to assume that `measure(0)` should measure qubit 0 and  not  the most significant qubit.

**Comment by BAMF0** [comment]
We should not confuse qubit representation with binary representation in our model

**Comment by edvinsternvik** [comment]
Yes, the problem was not with the measure function, but with the fact that the first element in the input array does not correspond to bit 0.

This is the way it was represented: [true, false, false] -> 100, in other words, the 1/true was bit number 2.
We changed this behavior in commit: #a1e265999691e69e50f586920fe7edc8b3defddb.
But we can discuss this later at the next meeting and revert back if we decide to.

**Comment by edvinsternvik** [comment]
Now, after this commit: [true, false, false] -> 001. Which produces the desired effect as described by elis.
